[16.0][MIG] mail_activity_done: Migration to 16.0
OCA/social pull request #1059
Opened 2023-02-01 11:06 UTC by ignissak

2023-02-01 14:01 UTC, ignissak commented
I had to rewrite setup of the test because for some reason the related field `res_model` didn't get populated and returned None on the test. Previously only `res_model_id` was assigned to the record.

2023-03-20 09:54 UTC, hbrunn requested changes

2023-03-20 09:54 UTC, hbrunn commented on mail_activity_done/hooks.py
> +    def _new_action_done(self, feedback=False, attachment_ids=None):
this monkey patch is potentially harmful and we don't need it. Would you mind cherry picking https://github.com/OCA/social/pull/1011 into your migration?

2023-03-20 09:55 UTC, hbrunn commented
/ocabot migration mail_activity_done

2023-05-19 08:35 UTC, CasVissers-360ERP commented on mail_activity_done/models/res_users.py
> +    def systray_get_activities(self):
I get traceback:

`UncaughtPromiseError
Uncaught Promise > Identifying field "id" is lacking a value on ir.model with 'and' identifying mode
Error: Identifying field "id" is lacking a value on ir.model with 'and' identifying mode
    at ModelIndexAnd.findRecord (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10340:159)
    at ModelManager.findFromIdentifyingData (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10377:88)
    at ModelManager._insert (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10471:62)
    at ModelManager._preInsertIdentifyingFieldsFromData (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10490:20)
    at ModelManager.findFromIdentifyingData (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10377:6)
    at ModelManager._insert (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10471:62)
    at ModelField._insertOtherRecord (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10235:35)
    at ModelField._setRelationInsertAndReplace (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10239:71)
    at ModelField.parseAndExecuteCommands (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10219:40)
    at ModelManager._update (https:/customer/web/assets/778166-4f926fb/web.assets_backend.min.js:10512:40)`

2023-05-22 16:24 UTC, closed without merging