[ADD] mass_mailing_list_sql: Integrate SQL queries for partner selection in mailing lists
OCA/social pull request #1102
Opened 2023-03-15 14:51 UTC by JoanSForgeFlow

The module allows users to define an SQL query for selecting partners to be included in the mailing list, providing greater flexibility in targeting recipients with complex criteria. 

By integrating this module, users can create more refined and targeted mailing lists, ultimately improving their email marketing strategies.

@JordiBForgeFlow @ForgeFlow

2023-03-20 07:49 UTC, GuillemCForgeFlow approved these changes
LGTM! 👍🏽 
Just as a nice to have, perhaps adding a user error when no users are found or when there is no partner with a valid email from all the contacts found, it would be great 👍🏽

2023-03-20 08:23 UTC, JordiBForgeFlow commented
@GuillemCForgeFlow Perhaps in this case the customers should just be filtered out. Sometimes the SQL may return 0 partners, and that may be ok. Would be bad to raise an error message. Today the results are 0, but tomorrow they may not be.

2023-05-25 07:50 UTC, mariadforgeflow approved these changes
LGTM!

2023-05-25 09:01 UTC, GuillemCForgeFlow requested changes

2023-05-25 09:01 UTC, GuillemCForgeFlow commented on mass_mailing_list_sql/__init__.py
> +from . import tests
```suggestion
```
Not needed.

2023-10-29 12:26 UTC, closed without merging