[FIX] email_template_qweb: Decode body when encoded
OCA/social pull request #114
Opened 2016-10-17 19:03 UTC by pedrobaeza

If the result is of type unicode, render method encodes it in utf-8.
We need to decode it in that case so that the rendering results correct.

2016-10-17 19:04 UTC, pedrobaeza commented
Please review @hbrunn @lasley @Yajo 

cc @Tecnativa

2016-10-17 21:34 UTC, lasley approved these changes
LGTM

Care to add a test covering this edge case?

2016-10-18 06:28 UTC, hbrunn approved these changes
yes, the extra test would be great

2016-10-18 06:29 UTC, pedrobaeza commented
It's very difficult to test this, and more without having more dependencies (I detected it sending a sales order), so I prefer not to spend time on it if you don't mind.

2016-10-18 07:46 UTC, Yajo commented
But... I don't understand... What was exactly the problem with plain utf8? Aren't all fields stored as such?

2016-10-18 07:50 UTC, pedrobaeza commented
No, they are passed directly to the wizard and accents appears incorrect

2016-10-18 07:55 UTC, yajo requested changes

2016-10-18 07:55 UTC, Yajo commented on email_template_qweb/models/mail_template.py
> +                    if isinstance(result[record_id]['body_html'], unicode):
Please add a comment above this, explaining why it is needed

2016-10-18 08:04 UTC, yajo approved these changes
I took the freedom to patch it myself. Let's merge :blush:

2016-10-18 08:21 UTC, merged