[13.0] mass_mailing_contact_active: Fix default value of active field in mass mailing subscription
OCA/social pull request #1152
Opened 2023-05-31 17:04 UTC by grindtildeath

Add default value in DB for active column.

Model mailing.contact.subscription is persisted using database table mailing_contact_list_rel.
This model is used for following O2m fields:
  - mailing.list.subscription_ids
  - mailing.contact.subscription_list_ids

However it is also used to materialize a M2m relation on following fields:
  - mailing.list.contact_ids
  - mailing.contact.list_ids

If records are added using O2m fields, the ORM will properly get the default value defined for the active field before inserting in the table. However, if records are added using M2m fields, the ORM will only use the foreign keys to insert since it's an associative table.

By defining a TRUE value as default for active field, we ensure the records added using the M2m fields will be active by default.

2023-05-31 17:43 UTC, grindtildeath commented
@pedrobaeza @yajo Looks like the reason why this fix is needed was the same reason why I had to segregate the testing on original PR with conflict on mass_mailing_custom_unsubscribe module: https://github.com/OCA/social/pull/871#issuecomment-1332144484
However, it was now breaking a test of mass_mailing_list_dynamic, that I could solve by forcing the propagation of the context key to avoid raising the ValidationError in the constraint.

Can you please have a look? :pray:

2023-05-31 18:21 UTC, pedrobaeza approved these changes

2023-06-01 08:17 UTC, yajo requested changes

2023-06-01 08:17 UTC, yajo commented on mass_mailing_contact_active/hooks.py
> +        """ALTER TABLE ONLY mailing_contact_list_rel ALTER COLUMN active SET DEFAULT TRUE;"""
You can move this to [the model's `init()` method](https://github.com/odoo/odoo/blob/9b9859a2f901cf4a434bd766ce86e91ea3cb4db8/odoo/models.py#L2561-L2565).

If you do so, this file can be removed.

2023-06-01 08:17 UTC, yajo commented on mass_mailing_contact_active/migrations/13.0.1.1.0/post-migrate.py
> +        """ALTER TABLE ONLY mailing_contact_list_rel ALTER COLUMN active SET DEFAULT TRUE;"""
If you follow my previous suggestion, this file can be removed too.

2023-06-01 13:34 UTC, grindtildeath commented
@yajo thx for the review, comments attended

2023-06-02 07:21 UTC, TDu approved these changes

2023-06-02 08:10 UTC, yajo approved these changes
Please squash the commits to merge. The bot can't do that yet https://github.com/OCA/oca-github-bot/issues/43.

2023-06-07 19:41 UTC, pedrobaeza commented
/ocabot merge nobump

2023-11-27 18:46 UTC, grindtildeath commented
@pedrobaeza seems the bot was out for lunch the last time you commented

2023-11-27 18:47 UTC, pedrobaeza commented
/ocabot merge nobump

2023-11-27 18:52 UTC, merged