[14.0] [MIG] mail_force_queue
OCA/social pull request #1166
Opened 2023-06-15 11:30 UTC by Kiplangatdan

2023-06-16 06:56 UTC, Kiplangatdan commented
@thomaspaulb Please review

2023-06-19 06:03 UTC, thomaspaulb requested changes

2023-06-19 06:03 UTC, thomaspaulb commented on mail_force_queue/models/mail_thread.py
> +            force_send = False
This can still be overridden by the [context key](https://github.com/OCA/OCB/blob/14.0/addons/mail/models/mail_thread.py#L2253), so, if you want to be sure it's set to False always, better set the context key itself.

2023-06-19 06:03 UTC, thomaspaulb commented on mail_force_queue/models/mail_thread.py
> +            send_after_commit=send_after_commit,
If you're not actually touching a named variable in your function, you can remove it in the function definition also, and it will be passed on as part of `**kwargs`

2023-06-19 06:03 UTC, thomaspaulb commented on mail_force_queue/readme/DESCRIPTION.rst
> +<https://github.com/odoo/odoo/issues/22148>`_.)
Maybe change this to:

```
In v10.0, this module solved possible TransactionRollbackError while deleting outgoing email (see `https://github.com/odoo/odoo/issues/22148
<https://github.com/odoo/odoo/issues/22148>`_.)

In v14.0, above problem should have been solved, but we still ran into cases with duplicate emails being sent out: first email on the original transaction, second email on the retried transaction after TransactionRollbackError. In our case, it was caused by concurrent transactions triggering the same write to the `message_main_attachment_id` field of an `account.move` record. We did not get to the bottom of this, but forward-ported this module as a workaround for these and other cases that may still exist.
```

2023-12-24 15:21 UTC, thomaspaulb commented
@Kiplangatdan ping

2024-06-09 12:30 UTC, closed without merging