[15.0][IMP] mail_activity_team: add multi-company check
OCA/social pull request #1196
Opened 2023-08-08 13:28 UTC by DavidJForgeFlow

When having two users in a activity team from different companies, it will raise an Exception of multicompany when adding the team to a document. This fix ensures that all the users in a team are from the same company (at least one of the companies available).

@ForgeFlow @etobella

2023-08-08 20:34 UTC, etobella reviewed
I don't like the option to add a required company field on teams. It might get confusing in some multicompany environments

2023-08-21 09:30 UTC, AaronHForgeFlow commented
My use case is the following. I am using activity teams "Helpdesk company1" and "Helpdesk company2". All the members of the team are assigned to new incoming tickets. If I assign a member of "Helpdesk company2" to a ticket in company1 the user will get access error, which is not desirable.  The only way to distinguish between the teams is the name of the team, and that leads to hardcode things.

2023-08-21 11:04 UTC, AaronHForgeFlow commented
Actually, I can filter members by company so I think this is not necessary at this point. I think we can close this.

2023-10-09 10:07 UTC, MiquelRForgeFlow requested changes

2023-10-09 10:07 UTC, MiquelRForgeFlow commented on mail_activity_team/models/mail_activity_team.py
> +from odoo.odoo.exceptions import ValidationError
```suggestion
from odoo.exceptions import ValidationError
```

2023-10-09 10:13 UTC, AaronHForgeFlow commented
I think this can be closed, not needed for now.

2023-10-09 11:04 UTC, closed without merging