[16.0][MIG] mass_mailing_event_registration_exclude: Migration to version 16.0
OCA/social pull request #1225
Opened 2023-10-03 15:10 UTC by carolinafernandez-tecnativa

- Standard migration to v16

@Tecnativa

TT45231

@pedrobaeza @chienandalu

2023-10-03 15:21 UTC, carolinafernandez-tecnativa commented
WIP

2023-10-04 18:46 UTC, pedrobaeza commented
/ocabot migration mass_mailing_event_registration_exclude

2023-10-04 18:48 UTC, pedrobaeza commented
Can you review the CI?

2023-10-05 08:44 UTC, fcvalgar approved these changes
Functional review

LGTM, thank you @carolinafernandez-tecnativa 

![image](https://github.com/OCA/social/assets/17847432/6d4f6668-231e-4780-a0dc-bcd77f2d17ad)

![image](https://github.com/OCA/social/assets/17847432/04d9d713-305a-4bb1-86cd-2de270b59b5a)

![image](https://github.com/OCA/social/assets/17847432/7786eddc-9636-42d2-80ae-6b131d5e30f6)

2023-10-05 10:12 UTC, chienandalu requested changes
When you're superseding, respect original PR commit attribution and work on top of it. Several changes are missing from that one btw.

2023-10-05 10:15 UTC, pedrobaeza commented
Well, sometimes the original PR doesn't have meaningful changes that should be respected, although this PR is now red, so maybe this is one of the cases where you should cherry-pick the commit from the other PR.

2023-10-09 11:54 UTC, carolinafernandez-tecnativa commented
> When you're superseding, respect original PR commit attribution and work on top of it. Several changes are missing from that one btw.

@chienandalu Done, I do not understand why tests are failing.
I run the test locally and all test passed:

<img width="1338" alt="image" src="https://github.com/OCA/social/assets/143796894/9e43456a-506d-43d8-98c7-79f618d66040">

If you see there is an error on that test, but when i run locally i got the same results:

![image](https://github.com/OCA/social/assets/143796894/b1659c62-3ae6-4c32-b1e1-db19463b8551)

2023-10-09 12:13 UTC, chienandalu commented
> @chienandalu Done, I do not understand why tests are failing. I run the test locally and all test passed:

You can try to reproduce it:

- Updating your local core code for Odoo/OCB to the latest commit
- Installing other modules in the repo that might be interacting with that condition

2023-10-09 12:13 UTC, chienandalu commented on mass_mailing_event_registration_exclude/models/res_partner.py
> +        res = super().search_count(domain, limit)
```suggestion
        res = super().search_count(domain, limit=limit)
```

2023-10-09 12:13 UTC, chienandalu commented on mass_mailing_event_registration_exclude/models/mailing_contact.py
> +        res = super().search_count(domain, limit)
```suggestion
        res = super().search_count(domain, limit=limit)
```

2023-10-09 12:13 UTC, chienandalu commented on mass_mailing_event_registration_exclude/models/event_registration.py
> +        res = super().search_count(domain, limit)
```suggestion
        res = super().search_count(domain, limit=limit)
```

2023-10-09 12:13 UTC, chienandalu commented on mass_mailing_event_registration_exclude/models/mailing.py
> +def event_filtered_ids(model, mailing_mailing_id, domain, field="email"):
It doesn't make much sense to keep this as a global method. Let's put the logic inside the mailing model

2024-01-04 18:35 UTC, pedrobaeza commented
Please check CI

2024-01-05 07:53 UTC, chienandalu approved these changes
LGTM Thanks :)

2024-01-05 07:54 UTC, pedrobaeza commented
/ocabot merge nobump

2024-01-05 08:04 UTC, merged