[FIX] Save and search recipient_address in lowercase
OCA/social pull request #125
Opened 2016-11-05 09:29 UTC by antespi

```recipient_address``` is an indexed field, but in all searchings we've been using ```=ilike```, then PostgreSQL can't use index for searching.
With this PR we save ```recipient_address``` in lowercase and search it using ```=```
This improve performance when calculating email_score, for instance.

Backport from https://github.com/OCA/social/pull/124

2016-11-05 10:12 UTC, pedrobaeza requested changes
You need to include a migration script that lower all existing emails and override partner write to make sure also that manual emails are in lower.

2016-11-05 10:53 UTC, pedrobaeza approved these changes
Thanks

2016-11-05 10:53 UTC, pedrobaeza commented
cc @Tecnativa

2016-11-05 13:24 UTC, susport commented
You need too override partner create to make sure also  that manual emails are in lower in the save.

2016-11-07 09:25 UTC, antespi commented
@susport It's done here: https://github.com/OCA/social/pull/125/files#diff-9bd607644e98dcc593ad45a5376183b8R48

2016-11-08 03:49 UTC, rafaelbn approved these changes

2016-11-08 06:53 UTC, pedrobaeza commented
@antespi, that's write method, not create method.

2016-11-08 16:18 UTC, merged