[17.0][MIG] mail_activity_done: Migration to 17.0
OCA/social pull request #1346
Opened 2024-04-08 18:36 UTC by jaydeep32

2024-04-08 21:43 UTC, hbrunn requested changes

2024-04-08 21:43 UTC, hbrunn commented on mail_activity_done/__manifest__.py
> +            # "mail_activity_done/static/src/js/mail_activity.esm.js",
well, it's your job in the migration to make it work

2024-06-05 09:58 UTC, vvrossem commented
Superseded by https://github.com/OCA/social/pull/1387

2024-06-21 10:52 UTC, StefanRijnhart commented
Closing in favour of https://github.com/OCA/social/pull/1387

2024-06-21 10:52 UTC, closed without merging