[17.0][MIG]mail_activity_reminder:Migration to 17.0
OCA/social pull request #1348
Opened 2024-04-09 09:05 UTC by bizzappdev

2024-04-15 06:13 UTC, hbrunn requested changes

2024-04-15 06:13 UTC, hbrunn commented on mail_activity_reminder/models/mail_thread.py
> +        # Added notif_layout in the set of valid parameter # T7487
please remove internal ticket numbers

2024-04-17 12:06 UTC, bizzappdev commented on mail_activity_reminder/models/mail_thread.py
> +        # Added notif_layout in the set of valid parameter # T7487
Removed. Thanks for noticing.

2024-04-22 09:34 UTC, hbrunn approved these changes

2024-08-29 14:03 UTC, dreispt approved these changes

2024-08-29 14:03 UTC, dreispt commented
/ocabot merge nobump

2024-08-29 14:16 UTC, merged