[17.0][MIG] email_template_qweb
OCA/social pull request #1361
Opened 2024-05-06 11:01 UTC by AnaisLForgeFlow

Standard Migration

@ForgeFlow

2024-05-06 20:32 UTC, pedrobaeza commented
/ocabot migration email_template_qweb

2024-05-07 13:22 UTC, GuillemCForgeFlow requested changes
For the rest, LGTM 👍🏿

2024-05-07 13:22 UTC, GuillemCForgeFlow commented on email_template_qweb/views/mail_template.xml
> +        <field name="model">mail.template</field>
perhaps would be great to add a name to these views, just as a little improvement. WDYT? 😄

2024-06-01 17:14 UTC, Rad0van commented
While it works fine in some contexts it doesn't work in this scenario:

1. There is a template and a related view created. In my case through data/email_templates.xml - the same way as in here: https://github.com/OCA/social/blob/a4192a637916b9b35c33e537e09e2e90b6edf940/email_template_qweb/demo/mail_template.xml#L1-L10
2. You open email composer from code using something similar to this: https://github.com/odoo/odoo/blob/7564e62114721d6e57c3f4c3d306612d5daaf2e0/addons/sale/models/sale_order.py#L843-L870
3. What you get is an empty email body

The reason being is this:

1. Mail composer computes the body here: https://github.com/odoo/odoo/blob/aff187f814998f4825da25f273eacef724686da3/addons/mail/wizard/mail_compose_message.py#L226-L235
2. Which calls this one: https://github.com/odoo/odoo/blob/aff187f814998f4825da25f273eacef724686da3/addons/mail/wizard/mail_compose_message.py#L1385-L1406

This line is the culprit:
`        template_value = self.template_id[template_fname] if self.template_id else False`

_template_fname_ contains "body_html" However that attribute is not defined in data XML so it returns with no body being rendered.

This usecase used to work in 16.0

2024-08-04 12:06 UTC, Rad0van commented on email_template_qweb/models/mail_template.py
> +                    }
```suggestion
                    custom_context = self._render_eval_context()
                    custom_context.update(
                        {
                            "object": record,
                            "email_template": self,
                            "format_datetime": lambda dt, tz=False, dt_format=False, lang_code=False: format_datetime(
                                self.env, dt, tz, dt_format, lang_code
                            ),
                        }
                    )
```

This is akin to #1249

2024-08-04 12:15 UTC, Rad0van commented
> While it works fine in some contexts it doesn't work in this scenario:
> 
> 1. There is a template and a related view created. In my case through data/email_templates.xml - the same way as in here: https://github.com/OCA/social/blob/a4192a637916b9b35c33e537e09e2e90b6edf940/email_template_qweb/demo/mail_template.xml#L1-L10
> 2. You open email composer from code using something similar to this: https://github.com/odoo/odoo/blob/7564e62114721d6e57c3f4c3d306612d5daaf2e0/addons/sale/models/sale_order.py#L843-L870
> 3. What you get is an empty email body :-(
> 
> The reason being is this:
> 
> 1. Mail composer computes the body here: https://github.com/odoo/odoo/blob/aff187f814998f4825da25f273eacef724686da3/addons/mail/wizard/mail_compose_message.py#L226-L235
> 2. Which calls this one: https://github.com/odoo/odoo/blob/aff187f814998f4825da25f273eacef724686da3/addons/mail/wizard/mail_compose_message.py#L1385-L1406
> 
> This line is the culprit: ` template_value = self.template_id[template_fname] if self.template_id else False`
> 
> _template_fname_ contains "body_html" However that attribute is not defined in data XML so it returns with no body being rendered.
> 
> This usecase used to work in 16.0

I see 2 possible fixes here:

1. override the __compute_body_ in _mail/wizard
/mail_compose_message.py_ - this does not feel exactly right but would do
2. sneak in some dummy body_html in our implementation of __generate_template_ - this does not feel right even more

Any ideas? Maybe @pedrobaeza ?

2024-08-05 06:46 UTC, pedrobaeza commented
Check where `self.template_id[template_fname]` is fed and fill it with the QWeb render result.

2024-08-05 07:46 UTC, Rad0van commented
> Check where `self.template_id[template_fname]` is fed and fill it with the QWeb render result.

Thanks for quick reply but I am not sure I follow :-(
In my opinion it is not fed anywhere - it is part of the mail.template: https://github.com/odoo/odoo/blob/aff187f814998f4825da25f273eacef724686da3/addons/mail/models/mail_template.py#L63-L65

For common templates it is filled in like this: https://github.com/odoo/odoo/blob/aff187f814998f4825da25f273eacef724686da3/addons/sale/data/mail_template_data.xml#L11-L41

In the __compute_body_ method it asks for "body_html" exactly.

So I fail to see how to feed the result QWeb render to it...

2024-08-08 17:24 UTC, pedrobaeza commented
Well, I didn't know as well the internals, but it seems the `__get__` of the model or something is overriden to get that weird behavior returning a specific body when you pass the XML-ID.

2024-10-25 07:42 UTC, simahawk commented
This modules is not needed anymore. See https://github.com/OCA/social/issues/1480
Do you see any case where it could still provide value?

2024-10-25 07:44 UTC, simahawk commented
> This modules is not needed anymore. See #1480 Do you see any case where it could still provide value?

ops, this is still v17 not v18. Sorry... However, as is not merged yet, we could evaluate if we can get rid of it already in v17.

2025-03-30 12:37 UTC, closed without merging