[9.0] [WIP] migration website_mail_snippet_vertical_resize_base module
OCA/social pull request #140
Opened 2016-12-20 07:59 UTC by cubells

- Updated README
- Updated views
- Updated js

cc @Tecnativa

2017-01-10 10:40 UTC, pedrobaeza commented
Is this finished?

2017-03-08 08:06 UTC, yajo requested changes

2017-03-08 08:06 UTC, Yajo commented on website_mail_snippet_vertical_resize_base/views/snippets.xml
> +<template id="snippet_hr"
This template ID seems misleading, copy-pasted from somewhere, right?

2017-04-30 10:14 UTC, rafaelbn commented
Hi @cubells , please could you review comments? Thanks!

2017-04-30 10:15 UTC, rafaelbn commented
Please @chienandalu could review this PR? Thanks

2017-04-30 11:27 UTC, pedrobaeza commented
This module has been finally dismissed.

2017-04-30 11:27 UTC, closed without merging