[16.0][MIG] <mail_server_by_user>: Migration to 16.0
OCA/social pull request #1422
Opened 2024-07-23 05:11 UTC by ByteMeAsap

2024-08-15 08:34 UTC, norlinhenrik approved these changes

2024-11-26 10:46 UTC, brambuijs approved these changes
Tested on v16. Functionally the module is working as expected.

2024-11-26 10:48 UTC, ByteMeAsap commented
@ChrisOForgeFlow, @pedrobaeza , can we have this merged?

2024-11-29 15:15 UTC, astirpe requested changes

2024-11-29 15:15 UTC, astirpe commented on mail_server_by_user/tests/test_mail_server_by_user.py
> +        # self.paynow_template = self.env.ref("mail.mail_notification_paynow")
Can you remove this commented code?

2024-12-20 09:23 UTC, hbrunn approved these changes

2025-05-25 12:40 UTC, closed without merging

2025-11-23 15:45 UTC, pcastelovigo commented
could this be reopened?