[MIG] mail_optional_follower_notification: Migration to 18.0
OCA/social pull request #1485
Opened 2024-10-30 09:59 UTC by carlosdynapps

2024-10-31 08:50 UTC, NachoAlesLopez reviewed
Functionally, LGTM. The field in the composer is missing its text, but other than that it, appears to work.

Also, mind taking a look at the last two commits? They are missing the module and version in the commit message. Can you rebase and add the correct information?

2024-10-31 08:50 UTC, NachoAlesLopez commented on mail_optional_follower_notification/wizard/mail_compose_message_view.xml
> +                    name="notify_followers"
This field is missing it's label. Without it, the checkbox doesn't have any text in the mail composer:
<img width="980" alt="Screenshot 2024-10-31 at 09 46 51" src="https://github.com/user-attachments/assets/08e81571-8181-4bb2-ae73-5a2c668b1d12">

2024-10-31 12:33 UTC, NachoAlesLopez approved these changes

2024-11-12 15:49 UTC, pedrobaeza requested changes
This should go to OCA/mail instead.

2024-12-06 10:51 UTC, closed without merging