[16.0][FIX] mail_composer_cc_bcc: fix duplicate key value error "unique_mail_message_id_res_partner_id_if_set"
OCA/social pull request #1493
Opened 2024-11-12 07:25 UTC by trisdoan

### Note
- Took over this PR: `https://github.com/OCA/social/pull/1428`

- Took this chance to
    - Fix `https://github.com/OCA/social/issues/1263`
       - it was fixed in `https://github.com/OCA/social/pull/1309`
       - But there is a case, described in `https://github.com/OCA/social/pull/1310#issuecomment-2186838432` , which was not covered.
    - Backport from `17.0`: using `res.partner `instead `product.template` in test. Otherwise, tests cannot run because model product.template is not in environment.

- Forward these commits to 17.0 in:
- Backport to 15.0: **WIP**

### Result

[mail_composer_cc_bcc_16.webm](https://github.com/user-attachments/assets/94096617-8331-4427-9364-ad5098ec63d9)

2024-11-12 07:35 UTC, trisdoan commented
DRAFT: fix test

2025-01-09 08:25 UTC, hbrunn requested changes
please rebase, upstream mail.mail._send code seems to have changed again

2025-01-09 08:25 UTC, hbrunn commented on mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
> +        if "purchase.order" in self.env:
please find a way to write this test without relying on models we don't have in the OCA CI run. Can't you test the same with ie users and the subtypes the mail module provides?

2025-01-14 05:34 UTC, trisdoan commented on mail_composer_cc_bcc/tests/test_mail_cc_bcc.py
> +        if "purchase.order" in self.env:
Hello @hbrunn, agreed, I just updated the test to mimic the flow

2025-01-14 07:04 UTC, hbrunn approved these changes

2025-12-14 12:45 UTC, closed without merging