Cid content change and data embeddings
OCA/social pull request #1499
Opened 2024-11-14 17:51 UTC by StephaneMangin

2024-12-12 13:15 UTC, hbrunn requested changes
tests are fixed in https://github.com/OCA/server-tools/pull/3146

2024-12-12 13:15 UTC, hbrunn commented on mail_embed_image/models/ir_mail_server.py
> +                response = requests.get(image_path, timeout=10)
please add a test case where we have an image with a relative url, I believe this will fail here

2024-12-12 13:15 UTC, hbrunn commented on mail_embed_image/views/res_config_settings_views.xml
> +                        Method used to embed images in HTML emails. CIDs attachment does not work with all email clients. Data SRC is more reliable.
that actually depends very much on the clients you target, with old outlooks it's the other way around. I'd propose not to make claim about what works better, and rather suggest to test with whatever are the expected mail clients

2024-12-19 10:47 UTC, StephaneMangin commented on mail_embed_image/views/res_config_settings_views.xml
> +                        Method used to embed images in HTML emails. CIDs attachment does not work with all email clients. Data SRC is more reliable.
Issue regarding Outlook has been tackled elsewhere. WIP
Need more testing regarding it before proposing.

2025-05-25 12:40 UTC, closed without merging