[16.0][UPD] mail_composer_cc_bcc: propose maintainer
OCA/social pull request #1520
Opened 2024-12-16 02:15 UTC by trisdoan

### Context
- @hailangvn  was the original author and maintainer of the module mail_composer_cc_bcc
- However, he is currently away from the office for personal reasons, and won't be back before a few months
- Hai and myself are part of the same company: Trobz
- So I propose myself as a maintainer of the module

2024-12-16 02:17 UTC, trisdoan commented
cc: @nilshamerlinck, @hbrunn

2024-12-18 22:42 UTC, hbrunn requested changes
please make this just one commit adding you as maintainer and leave the rest to the other PRs

2024-12-20 02:08 UTC, nilshamerlinck approved these changes

2024-12-20 09:18 UTC, hbrunn approved these changes

2024-12-21 05:28 UTC, hbrunn commented
/ocabot merge nobump

2024-12-21 05:33 UTC, merged