Add files via upload
OCA/social pull request #154
Opened 2017-02-27 07:10 UTC by tpxxx

Applied fix 09f8219 and 5d2a3bd according to discussion with Pedro M. Baeza to 10.0 Branch in order to solve problem with characters like ä ö ü etc. in QWeb email templates

2017-02-27 10:16 UTC, hbrunn commented
please cherry-pick those commits

2017-03-17 02:23 UTC, pedrobaeza requested changes
Use the cherry-pick command as stated by my colleague

2017-04-30 10:10 UTC, rafaelbn commented
Hi @tpxxx , thanks for this contribution. Please, are you going to attend comments?

2018-08-28 11:42 UTC, hbrunn commented
closing due to lack of activity

2018-08-28 11:42 UTC, closed without merging