[add] mail_digest
OCA/social pull request #158
Opened 2017-03-24 08:38 UTC by simahawk

This module allows users/partners to:

- select "digest" mode in their notification settings
- with digest mode on select a frequency: "daily" or "weekly"
- configure specific rules per message subtype (enabled/disabled)

and receive or not receive any email notification for a given subtype.

This module is needed by its CMS integration module [cms_notifications](https://github.com/simahawk/website-cms/tree/add-cms_notifications-PR/cms_notifications)

2017-03-24 08:46 UTC, simahawk commented
TODO: check / fix failing tests w/ other social modules.

2017-03-24 23:38 UTC, simahawk commented
@antespi @pedrobaeza I'm checking failing tests. I see 

```bash
2017-03-24 08:42:43,626 5399 ERROR openerp_test openerp.addons.mail_tracking_mailgun.models.mail_tracking_email: Mailgun: Database 'bad_db' is not the current database
[...]
2017-03-24 08:42:44,481 5399 ERROR openerp_test openerp.addons.mail_tracking_mailgun.models.mail_tracking_email: Mailgun: event type 'bad_event' not supported
```

and other similar errors, both on travis and on my local setup (with just mail_tracking tests running).

Actually I found the same errors in the original PR https://travis-ci.org/OCA/social/jobs/161414564

Is there any particular setting to run tests for mail_tracking or can I just ignore them?

2017-03-27 15:45 UTC, pedrobaeza commented
AFAIK, these are the intended behavior of the tests, proving a wrong DB in them to see if it fails, so this is not problem for the status (and indeed Travis is green).

2017-03-29 14:30 UTC, simahawk commented
@pedrobaeza is green since I fixed my stuff :) I wanted to make I didn't break anything else before debugging. Tnx anyway.

2017-04-26 14:04 UTC, dreispt commented on mail_digest/models/res_partner.py
> +        # TODO: what to do when a partner updates frequency?
> what to do when a partner updates frequency?
Frequency tells how often we will try to send a digest to the Partner.
Whenever we hit that time, all unsent messages will be collected into that digest, and marked as sent.
It you look at it this way, the answer is trivial.
With this design, the frequency is irrelevant for the `mail.digest` queue; it only matters for the digest mail process.

2017-04-26 19:52 UTC, simahawk commented on mail_digest/models/res_partner.py
> +        # TODO: what to do when a partner updates frequency?
yep, you are right here. In your opinion, is there any other place where this should be taken into account?

2017-04-27 07:49 UTC, dreispt commented on mail_digest/models/res_partner.py
> +        # TODO: what to do when a partner updates frequency?
Can't remember any. Frequency should only be relevant to trigger the "cron job".

2017-05-30 07:23 UTC, simahawk commented
@pedrobaeza @dreispt anything else to do here but rebase?

2017-05-30 08:50 UTC, guewen approved these changes

2017-05-30 15:00 UTC, simahawk commented
rebased!

2017-06-08 13:54 UTC, simahawk commented
@pedrobaeza @rafaelbn @dreispt any stopper here?

2017-06-08 16:48 UTC, pedrobaeza requested changes
Little changes

2017-06-08 16:48 UTC, pedrobaeza commented on mail_digest/__openerp__.py
> +        # TODO: fix permissions (only admin now)
Is still this TODO?

2017-06-08 16:48 UTC, pedrobaeza commented on mail_digest/README.rst
> +to receive or not receive any email notification for a given subtype.
"to receive or to not receive"

2017-06-19 06:51 UTC, simahawk commented
@pedrobaeza updated. Should be ready for merge ;)

2017-06-19 07:46 UTC, pedrobaeza approved these changes

2017-06-19 07:46 UTC, merged