[MIG] mass_mailing_partner: Migration to 10.0
OCA/social pull request #171
Opened 2017-06-14 18:49 UTC by chienandalu

cc @Tecnativa

2017-06-15 07:31 UTC, yajo requested changes
Please clean up commit history

2017-06-19 00:44 UTC, pedrobaeza requested changes
Add your copyright in the files you touch and check Travis status. It should be green.

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/README.rst
> +NOTE: When upgrading from version 1.0.0, no mass mailing statistics matching
This note can be removed and it doesn't apply anymore.

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/README.rst
> +`here <https://github.com/OCA/crm/issues/new?body=module:%20mass_mailing_partner%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_
Remove this part according new README template

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/README.rst
> +License
Remove this unneeded section

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/__manifest__.py
> +              "Antiun Ingeniería S.L., "
Remove Antiun and Serv. Tecnol. ...

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/models/mail_mass_mailing_contact.py
> +    @api.one
Don't put `@api.one` here.

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/models/mail_mass_mailing_contact.py
> +    @api.one
Rewrite the method to be `@api.multi` or this will hit performance.

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/models/res_partner.py
> +    @api.one
Rewrite it for `@api.multi`

2017-06-19 00:44 UTC, pedrobaeza commented on mass_mailing_partner/models/res_partner.py
> +    @api.one
Make it `@api.multi`

2017-06-20 16:38 UTC, pedrobaeza requested changes

2017-06-20 16:38 UTC, pedrobaeza commented on mass_mailing_partner/models/res_partner.py
> +        self.mass_mailing_stats_count = len(self.mass_mailing_stats)
This needs a `for` loop

2017-06-20 16:38 UTC, pedrobaeza commented on mass_mailing_partner/models/res_partner.py
> +        self.mass_mailing_contacts_count = len(self.mass_mailing_contact_ids)
This needs a `for`loop

2017-06-21 16:54 UTC, chienandalu commented
@pedrobaeza @Yajo Changes done. Travis is failing on `mail_tracking` and `mail_tracking_mailgun`

2017-06-22 07:26 UTC, yajo requested changes

2017-06-22 07:26 UTC, Yajo commented on mass_mailing_partner/__manifest__.py
> +    "author": "Tecnativa, "
Missing website

2017-06-22 07:26 UTC, Yajo commented on mass_mailing_partner/i18n/mass_mailing_partner.pot
> +# Translation of Odoo Server.
This file should not exist

2017-06-22 07:26 UTC, Yajo commented on mass_mailing_partner/models/res_partner.py
> +                  "mailing lists. Email must be assigned." % self.name))
The string modulo must be after the translation, not before.

2017-06-22 07:26 UTC, Yajo commented on mass_mailing_partner/wizard/partner_mail_list_wizard.xml
> +                or
Remove the *or*

2017-06-22 08:10 UTC, chienandalu commented on mass_mailing_partner/models/res_partner.py
> +                  "mailing lists. Email must be assigned." % self.name))
@Yajo I'm not sure about what you mean here :confused:

2017-06-26 08:51 UTC, chienandalu commented
@Yajo @pedrobaeza Changes done

2017-06-26 08:53 UTC, yajo approved these changes
Code review

2017-08-03 11:20 UTC, pedrobaeza approved these changes

2017-08-03 12:09 UTC, pedrobaeza commented
Please check errors

2017-08-03 13:17 UTC, chienandalu commented
@pedrobaeza Errors seem to be unrelated. Rebasing to rebuild tests and see.

2017-08-03 13:35 UTC, chienandalu commented
@pedrobaeza Well, this is runbot's log now :confused: 

```
Unable to find image 'oca-social:5c095f6_3' locally
docker: Error response from daemon: repository oca-social not found: does not exist or no pull access.
See 'docker run --help'.
```

2017-08-03 13:38 UTC, pedrobaeza commented
Uhm, right, please try to fix main branch in other PR.

2017-08-30 16:04 UTC, chienandalu commented
@pedrobaeza It's all green now

2017-08-30 17:02 UTC, merged