[FIX] Name of overridden method
OCA/social pull request #209
Opened 2017-11-06 06:56 UTC by StefanRijnhart

As per https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_followers.py#L138. @Yajo, this one is a bit of a mystery. I could not find any trace of this method name with the preceding underscore.

2017-11-06 07:00 UTC, pedrobaeza commented
There was a previous attempt at #176, but it misses the tests fix.

2017-11-06 07:10 UTC, pedrobaeza commented
Please change module version number

2017-11-07 12:08 UTC, yajo requested changes
Indeed the code fix is quite obvious, but please make Travis happy 😊

2017-11-07 18:20 UTC, StefanRijnhart commented
@Yajo I fixed the lint error related to this change but the odoo/odoo build fails just like on the main branch (and I don't know how to fix timeouts in http tests anyway)

2017-11-07 18:23 UTC, pedrobaeza commented
Agh, same problem everywhere out of Odoo itself. There's a general problem with Travis + wkhtmltopdf, which reproduces the same way. Don't know if this one is the same.

2017-11-08 11:46 UTC, yajo approved these changes
Besides, [there's an error in another addon](https://travis-ci.org/OCA/social/jobs/298681131#L1476-L1513).

OK, not blocking then

2017-11-15 13:31 UTC, hbrunn approved these changes

2017-11-15 13:32 UTC, merged