[MIG][11.0] mail_digest
OCA/social pull request #225
Opened 2018-01-18 14:03 UTC by simahawk

NOTE: I've tried to squash the 2 OCA transbot commits but I get tons of conflicts...

2018-01-19 08:55 UTC, grindtildeath requested changes
It seems, there's something wrong with message and mail_id params, as a few are unused, Otherwise, looks good !

2018-01-19 08:55 UTC, grindtildeath commented on mail_digest/data/ir_cron.xml
>      <data noupdate="1">
<data> to remove.

2018-01-19 08:55 UTC, grindtildeath commented on mail_digest/models/mail_digest.py
>          subtype_id = subtype_id or message.subtype_id
Looks like this can be removed, as it isn't used in the function.

2018-01-19 08:55 UTC, grindtildeath commented on mail_digest/models/mail_digest.py
> +    def _get_by_user(self, user, mail_id=False):
`mail_id` should be renamed `mail`

2018-01-19 08:55 UTC, grindtildeath commented on mail_digest/models/mail_digest.py
>              ('mail_id', '=', mail_id),
`mail_id` is then `mail.id`

2018-01-19 08:55 UTC, grindtildeath commented on mail_digest/models/mail_digest.py
> +    def _get_or_create_by_user(self, user, message=None, mail_id=False):
Again `mail_id` > `mail`,  `message=None` to remove, as it's not used

2018-01-19 08:55 UTC, grindtildeath commented on mail_digest/models/mail_digest.py
> +        existing = self._get_by_user(user, mail_id=mail_id)
`mail_id=mail_id` > `mail=mail`

2018-01-19 08:55 UTC, grindtildeath commented on mail_digest/models/res_users.py
> +            import pdb; pdb.set_trace()
Seems this should be removed.

2018-01-19 09:04 UTC, simahawk commented
@grindtildeath obsolete params removed. tnx :)

2018-01-19 09:41 UTC, grindtildeath reviewed
Two `<data>`XML tags to remove and it's fine for me :+1:

2018-01-19 09:41 UTC, grindtildeath commented on mail_digest/data/ir_cron.xml
> +    <data noupdate="1">
Still this tag to remove.

2018-01-19 09:41 UTC, grindtildeath commented on mail_digest/data/config_param.xml
> +    <data noupdate="1">
Still this tag to remove.

2018-01-19 09:44 UTC, simahawk commented
@grindtildeath done

2018-01-19 09:50 UTC, grindtildeath approved these changes

2018-01-25 10:30 UTC, mpanarin approved these changes
LGTM

2018-01-30 08:03 UTC, tschanzt commented on mail_digest/models/mail_digest.py
> +    def create_or_update(self, partners, message):
is there any reason to still use the partner here? specially since you then get the user_id from the partner.

2018-01-30 08:30 UTC, simahawk commented on mail_digest/models/mail_digest.py
> +    def create_or_update(self, partners, message):
some reasons:
1. this method is called by res.partner `_notify` method as notification are sent to users but attached to partners. I like to keep the 2 things tied;
2. message/email recipients are partners (as in std notifications). Again like to keep this in line.

2018-01-30 09:24 UTC, tschanzt commented on mail_digest/models/mail_digest.py
> +    def create_or_update(self, partners, message):
ok, that makes sense.

2018-01-30 09:24 UTC, tschanzt approved these changes

2018-02-01 09:16 UTC, hbrunn commented
it's quite hard for me to separate the old commits from the new ones, @simahawk, can you check this?

2018-02-01 09:37 UTC, simahawk commented
@hbrunn the last 3 commits. The former are improvements coming from v10 that were not ported yet.

2018-02-01 09:43 UTC, hbrunn commented
thanks, I was doing something stupid before. I miss a migration script, but given we don't have rules about that to my knowledge, I won't block on this. Any reason not to provide one? Should be just a couple of SQL statements and make the upgrade experience much better.

2018-02-01 09:51 UTC, simahawk commented
@hbrunn main reason, honestly: not needed for my project and not sure I can spend time on it.
I provided info in the README on how to achieve that... in case someone is willing to help :wink:

2018-02-01 10:04 UTC, merged

2018-02-01 10:06 UTC, hbrunn commented
@simahawk fair enough. But you inspired me to make this PR: https://github.com/OCA/maintainer-tools/pull/324