[11][MIG] email_template_qweb: Migration to 11.0
OCA/social pull request #250
Opened 2018-03-25 18:29 UTC by celm1990

PR replace #249 
Sorry for create and close various PR. Is my first contribution

2018-03-25 18:34 UTC, pedrobaeza commented
@celm1990 next time, for avoiding opening more PRs, you just need to use `git push -f` for overwriting the branch with the new contents. Please try next time or ask me and I'll teach you.

2018-04-06 07:33 UTC, simahawk requested changes

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/README.rst
> +    :target: https://runbot.odoo-community.org/runbot/205/10.0
/11.0

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/README.rst
> +For further information, please visit:
update whole README according to latest template https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/__init__.py
> +# -*- coding: utf-8 -*-
remove coding headers

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/__init__.py
> +# © 2016 Therp BV <http://therp.nl>
replace (c) symbol w/ "Copyright"

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/__manifest__.py
> +    "summary": "Use the QWeb templating mechanism for emails",
add `'website': 'https://github.com/OCA/social',`

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/models/mail_template.py
> +    body_view_arch = fields.Text(related=['body_view_id', 'arch'])
`related='body_view_id.arch'`?

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/models/mail_template.py
> +        for record_id, this in self.get_email_template(res_ids).items():
we are not in JS here: change `this` w/ `record`?

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/models/mail_template.py
> +                    # Some wizards, like when sending a sales order, need this
still the case w/ Odoo 11 and py3?

2018-04-06 07:33 UTC, simahawk commented on email_template_qweb/tests/test_mail_template_qweb.py
> +            'Did not rcv rendered template in response. Got: \n%s\n' % (
s/rcv/??? "receive"?

2018-04-09 07:38 UTC, hbrunn commented on email_template_qweb/models/mail_template.py
> +                    if not isinstance(body_html, str):
I think we'll be better off with using https://github.com/OCA/OCB/blob/11.0/odoo/loglevels.py#L43 here

2018-04-17 15:24 UTC, tschanzt requested changes
Only some minor nitpicking.

2018-04-17 15:24 UTC, tschanzt commented on email_template_qweb/models/mail_template.py
> +
can your remove the empty line here?

2018-04-17 15:24 UTC, tschanzt commented on email_template_qweb/models/__init__.py
> +
can your remove the empty line here?

2018-04-26 10:51 UTC, simahawk requested changes
@celm1990 LGTM but module version. @tschanzt  can you update your review?
@hbrunn can you do yours? :)

2018-04-26 10:51 UTC, simahawk commented on email_template_qweb/__manifest__.py
> +    "version": "10.0.1.0.0",
11.0.1.0.0

2018-04-26 10:52 UTC, simahawk commented
also, whe you are done, squash your commits pls :)

2018-04-26 13:30 UTC, tschanzt approved these changes
Apart from the things @simahawk mentioned it looks good to me.

2018-04-26 13:34 UTC, hbrunn approved these changes
same here

2018-04-27 11:57 UTC, pedrobaeza commented
@celm1990 please make the little remaining things to merge this.

2018-05-10 02:23 UTC, celm1990 commented
@pedrobaeza is ok or something is missing???

2018-05-10 07:08 UTC, simahawk commented
@celm1990 this comment seems unattended https://github.com/OCA/social/pull/250#discussion_r179678776
compare "bug tracker" and "contributor" sections w/ the template I linked ;)

2018-05-10 07:09 UTC, simahawk approved these changes
Overall LGTM. Approving to not get back, but check README again ;)

2018-05-10 14:31 UTC, celm1990 commented
@simahawk Done, update readme.rst.

2018-05-11 01:43 UTC, rafaelbn approved these changes

2018-05-11 01:43 UTC, rafaelbn commented on email_template_qweb/README.rst
> +#. Go to ...
You can delete this line

2018-05-15 14:36 UTC, pedrobaeza approved these changes

2018-05-15 14:57 UTC, merged