[MIG] mail_improved_tracking_value: migration to Odoo 11
OCA/social pull request #254
Opened 2018-04-05 14:42 UTC by mpanarin

migration of module https://github.com/OCA/social/pull/170

2018-04-06 12:14 UTC, TDu approved these changes
LGTM

2018-04-09 07:54 UTC, simahawk requested changes
as we already have many reviews on v10 I think you have to include that commit and add a new one for v11 mig

2018-04-11 08:14 UTC, guewen approved these changes

2018-04-14 00:09 UTC, rafaelbn commented
Thank you! Agree with @simahawk  in https://github.com/OCA/social/pull/254#pullrequestreview-110357733 

Also is possible to add some test. it should be very nice codecov/patch — 23.8% of diff hit (target 87.44%)

2018-04-14 00:10 UTC, rafaelbn approved these changes

2018-05-02 19:34 UTC, rafaelbn commented
Hi @mpanarin , please could you attend @simahawk comments ? Thank you!

2018-07-06 12:03 UTC, ThomasBinsfeld approved these changes

2018-07-06 12:03 UTC, pedrobaeza commented
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

2018-08-10 16:40 UTC, tdombos commented
Gives an error message if trying to delete a one2may line tracked:
> Odoo Server Error - Missing Record 
> Record does not exist or has been deleted.

2019-06-26 11:17 UTC, mreficent commented on mail_improved_tracking_value/models/mail_tracking_value.py
> +                    names = ', '.join(source.mapped('display_name'))
```suggestion
                    names = ', '.join(
                        [s.display_name for s in source.exists()])
```

If you do this, you avoid the `Missing Record` error for one2many, but then the message doesn't show the deleted record 😕

2019-06-26 11:35 UTC, mreficent commented
In fact, the best way I found to track a one2many is creating a computed char and tracking it, like I did in https://github.com/Eficent/ao-odoo/pull/121/files#diff-4a0c09c64bab72fb4713db84f0c2358dR25.

2021-02-22 14:33 UTC, MiquelRForgeFlow commented
Superseded by https://github.com/OCA/social/pull/254.

2021-12-06 13:49 UTC, closed without merging