11.0 mig mail attach existing attachment
OCA/social pull request #260
Opened 2018-04-17 17:27 UTC by ernestotejeda

2018-05-14 10:49 UTC, hbrunn requested changes

2018-05-14 10:49 UTC, hbrunn commented on mail_attach_existing_attachment/tests/test_mail_attach_existing_attachment.py
> +        # self.partner_01 = self.env.ref('base.res_partner_1')
remove this line, then we're fine I think

2018-06-05 05:59 UTC, rafaelbn commented
cc @Tecnativa

2018-06-13 15:43 UTC, rafaelbn approved these changes
Tested in runbot :+1:  

Please @hbrunn you comments are attended could you check it ? Thanks!

2018-06-13 15:46 UTC, hbrunn approved these changes

2018-06-13 15:46 UTC, merged