[WIP][MIG] mass_mailing_custom_unsubscribe: Migration to 11.0
OCA/social pull request #279
Opened 2018-05-25 16:56 UTC by chienandalu

WIP as the contacts relation to the lists has changed quite a bit (now one mailing contact can belong to multiple lists) so some parts must be reworked.

cc @Tecnativa

2018-05-28 07:10 UTC, Yajo commented
Check those :x:  please

2018-05-28 07:13 UTC, chienandalu commented
This WIP yet :smile: The module has to be reworked as the contact<->list relation has changed in v11

2018-05-29 16:46 UTC, chienandalu commented
@Yajo This bug https://github.com/odoo/odoo/pull/24969 has to be fixed in order to get the tours working

2018-06-01 12:20 UTC, rafaelbn commented
@Yajo @chienandalu this FIX is needed yes https://github.com/odoo/odoo/pull/24969 and we should propose it in OCB if Odoo don't accept it. Do we have and OPW?

2018-06-04 11:50 UTC, Yajo commented on mass_mailing_custom_unsubscribe/templates/mass_mailing_contact_reason.xml
> +    <!---->
:fire:

2018-06-04 11:50 UTC, Yajo commented on mass_mailing_custom_unsubscribe/models/mail_mass_mailing.py
> +                pass
:fire:

2018-06-04 11:50 UTC, Yajo commented on mass_mailing_custom_unsubscribe/models/mail_mass_mailing.py
> +        records = self.env[model._name].browse(res_ids)
`model.browse`?

2018-06-04 11:50 UTC, Yajo commented on mass_mailing_custom_unsubscribe/models/mail_mass_mailing.py
> +            active_test=False)
:thinking: why the context?

2018-06-04 11:50 UTC, Yajo commented on mass_mailing_custom_unsubscribe/static/src/js/partner.tour.js
> +                trigger: "body:not(:has(#reason_form)) .alert-success:contains('You have been successfully unsubscribed!')",
What if you are subscribing? Shouldn't this be kept?

2018-06-04 11:50 UTC, Yajo commented on mass_mailing_custom_unsubscribe/templates/mass_mailing_contact_reason.xml
> +                   t-att-checked="'checked' if contact['opt_out'] == False else None"/>
`is` instead of `==`

2018-06-04 11:50 UTC, Yajo commented on mass_mailing_custom_unsubscribe/controllers/main.py
> +                        contact.list_ids <= mailing.contact_list_ids
I think that, [given upstream basically broke this in v11](https://github.com/odoo/odoo/blob/6b0c7a33d6b749d79232082fb5716e6cf36a9967/addons/website_mass_mailing/views/unsubscribe_templates.xml#L20-L30), you can just add a new qcontext key like this:

```python
"lists": contact.list_ids | request.env["mail.mass_mailing.list"].search([["not_cross_unsubscriptable", "=", False]]),
```

Then iterate over those lists in the view and render 1 checkbox for each of them if contact is subscribed to any of them.

Then, when user checks some and unchecks others, record 1 `mail.mass_mailing.unsubscription` per contact+list combination.

2018-06-12 12:36 UTC, pedrobaeza commented
Travis is still red

2018-06-12 14:03 UTC, yajo requested changes
Great!

2018-06-12 14:03 UTC, Yajo commented on mass_mailing_custom_unsubscribe/hooks.py
> +            for list in contact.list_ids:
I think you should use upper level methods for this, and don't override builtin `list`:

```python
for contact in contacts:
    if len(contact.list_ids) <= 1:
        continue
    list_1 = contact.list_ids[0]
    for list_ in contact.list_ids - list_1:
        contact.copy({"list_ids": [(6, 0, list_.ids)]})
    contact.list_ids = list_1
```

2018-06-12 14:03 UTC, Yajo commented on mass_mailing_custom_unsubscribe/readme/ROADMAP.rst
> +  to land in version 12, this module fallsback to the version 10 behaviour in
falls back

2018-06-12 14:03 UTC, Yajo commented on mass_mailing_custom_unsubscribe/readme/ROADMAP.rst
> +  wich one contact belonged to just one list.
which

2018-06-12 15:11 UTC, rafaelbn commented
all is :green_heart: here! Great! @Yajo last technical review? I will test it functionally

2018-06-12 15:19 UTC, Yajo commented
It's just above :wink:

2018-06-12 15:41 UTC, chienandalu commented
@Yajo Fixed

2018-06-12 16:04 UTC, rafaelbn commented
@chienandalu :rofl: fixed? It was :green_apple: now is :red_circle:

2018-06-12 16:23 UTC, chienandalu commented
@rafaelbn :green_heart: as  :green_apple:

2018-06-13 08:16 UTC, yajo approved these changes
Great!

2018-06-13 08:23 UTC, pedrobaeza approved these changes

2018-06-13 08:23 UTC, merged