12.0 mig mail_attach_existing_attachment
OCA/social pull request #317
Opened 2018-11-05 15:22 UTC by ernestotejeda

Cc @Tecnativa

2018-11-07 10:25 UTC, chienandalu requested changes

2018-11-07 10:25 UTC, chienandalu commented on mail_attach_existing_attachment/readme/USAGE.rst
> +.. figure:: static/description/attachment.png
This isn't valid anymore, isn't it?

2018-11-08 17:40 UTC, pedrobaeza commented
@ernestotejeda please squash directly all migration commits as there are no reviews yet

2018-11-08 17:51 UTC, ernestotejeda commented on mail_attach_existing_attachment/readme/USAGE.rst
> +.. figure:: static/description/attachment.png
image path was incorrect, i already have fixed

2018-11-09 08:20 UTC, chienandalu commented on mail_attach_existing_attachment/readme/USAGE.rst
> +.. figure:: mail_attach_existing_attachment/static/description/attachment.png
I mean Odoo removed the option from the UI: https://github.com/odoo/odoo/issues/27760 So this instruction isn't valid

2018-12-05 08:06 UTC, chienandalu approved these changes
Great! :+1:

2018-12-05 09:26 UTC, pedrobaeza approved these changes

2018-12-05 09:50 UTC, merged

2019-02-05 17:24 UTC, sswapnesh commented on mail_attach_existing_attachment/readme/USAGE.rst
> +.. figure:: mail_attach_existing_attachment/static/description/attachment.png
@chienandalu I don't know the module functionality but https://github.com/odoo/odoo/pull/30636 adds few options related to this