[MIG] fetch_thread_default: Migration to 11.0
OCA/social pull request #339
Opened 2018-12-03 12:38 UTC by chienandalu

This module extends the functionality of mail fetching to support choosing a
mail thread that acts as a mail sink and gathers all mail messages that Odoo
does not know where to put.

cc @Tecnativa

2018-12-03 12:47 UTC, pedrobaeza requested changes

2018-12-03 12:47 UTC, pedrobaeza commented on fetchmail_thread_default/models/fetchmail_server.py
> +        super(FetchmailServer, self).onchange_server_type()
Always return possible values of onchange.

2018-12-03 12:47 UTC, pedrobaeza commented on fetchmail_thread_default/tests/test_fetchmail.py
> +    # def test_emptying_default_thread(self):
Don't comment tests

2018-12-03 13:14 UTC, chienandalu commented
@pedrobaeza Fixed

2018-12-03 13:16 UTC, pedrobaeza approved these changes
If CIs go well

2018-12-04 11:33 UTC, chienandalu commented
ping @Yajo

2018-12-04 12:34 UTC, yajo approved these changes

2018-12-04 12:38 UTC, merged