[10.0][MIG] Migration of base_mail_bcc
OCA/social pull request #365
Opened 2019-03-08 13:35 UTC by fkantelberg

Hello,
because we need this module in odoo 10 I want to share the migrated version

2019-04-25 21:25 UTC, tbaden requested changes
thanks for the work 👍 
i did a code review.
just some minor details

2019-04-25 21:25 UTC, tbaden commented on base_mail_bcc/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
please use the new readme generator (https://github.com/OCA/maintainer-tools)

2019-04-25 21:25 UTC, tbaden commented on base_mail_bcc/__init__.py
> +# © 2014-2016 Thomas Rehn (initOS GmbH)
copyright s/2014-2016/2014-2019/ in all files

2019-04-25 21:25 UTC, tbaden commented on base_mail_bcc/models/ir_mail_server.py
> +        return super(IrMailServer, self).send_email(
possible readability improvement (not mandatory)

```
return super(IrMailServer, self).send_email(
            message, 
            mail_server_id=mail_server_id,
            smtp_server=smtp_server,
            smtp_port=smtp_port,
            smtp_user=smtp_user,
            smtp_password=smtp_password,
            smtp_encryption=smtp_encryption,
            smtp_debug=smtp_debug
        )
```

2019-04-26 12:34 UTC, fkantelberg commented
@tbaden Thanks for the review. I did the mentioned changes.

2019-04-26 12:39 UTC, tbaden approved these changes
thanks

2019-04-26 13:00 UTC, tbaden requested changes
please check travis and runbot
runbot:
WARNING: module base_mail_bcc: description is empty !
travis:
ERROR openerp_test odoo.addons.mail_sendgrid.tests.test_mail_sendgrid: FAIL

2019-06-13 08:52 UTC, hbrunn commented
please rebase

2022-03-06 12:28 UTC, closed without merging