[12.0][FIX] mail_activity_done module
OCA/social pull request #380
Opened 2019-05-06 08:00 UTC by ageficent

This PR intends to fix this issue: #379 

cc ~ @jbeficent @emagdalenaC2i

2019-05-06 08:58 UTC, emagdalenaC2i approved these changes
It works fine. Thanks

@ageficent Could you increment the version number?

2019-05-06 12:11 UTC, emagdalenaC2i commented
@ageficent and @jbeficent Other non related issue in this module:

If you install this module it handle correctly the existing activities. 
But if you 
1) install the module, 
2) create a few activities and make some of them as done

When you uninstall the module, that activities are no longer marked as done.

This can be an important issue if you have create and done thousand of activities.

2019-05-07 08:14 UTC, emagdalenaC2i commented
An other issue. You can check this in runbot.
If you go to Contacts, and set the filter "Late activities" it will show all the late activities (done or not done)
![image](https://user-images.githubusercontent.com/24428859/57283993-9e114e00-70b0-11e9-929f-97d77a052e34.png)
![image](https://user-images.githubusercontent.com/24428859/57284177-f0526f00-70b0-11e9-9c10-1fc59ec6f4e6.png)

2019-05-07 19:23 UTC, emagdalenaC2i commented
Tested and code review
@ageficent Could you increment the version number?

2019-05-13 12:40 UTC, emagdalenaC2i commented
@jbeficent are this PR ready to merge?

2019-06-06 10:00 UTC, emagdalenaC2i commented
@jbeficent and @ageficent 
Please, could you finish this PR... and remember the issue reported by @aitorbouzas #386

2019-06-11 14:50 UTC, MiquelRForgeFlow approved these changes

2019-06-11 14:59 UTC, mreficent commented
@ageficent could you cherry-pick https://github.com/OCA/social/pull/395?

2019-06-11 15:04 UTC, ageficent commented
> @ageficent could you cherry-pick #395?

Done :+1:

2019-06-11 15:16 UTC, MiquelRForgeFlow requested changes

2019-06-11 15:16 UTC, mreficent commented on mail_activity_done/migrations/11.0.2.0.0/pre-migration.py
> +# Copyright 2019 Eficent <http://www.eficent.com>
change number version of the folder

2019-06-11 15:20 UTC, MiquelRForgeFlow requested changes

2019-06-11 15:20 UTC, mreficent commented on mail_activity_done/views/mail_activity_views.xml
> +    <record id="res_partner_view_search_inherit_mail" model="ir.ui.view">
apply in this view same changes as done above

2019-06-12 10:11 UTC, mreficent commented on mail_activity_done/migrations/11.0.2.0.0/pre-migration.py
> +# Copyright 2019 Eficent <http://www.eficent.com>
and move it to post-migration 😆

2019-06-12 10:18 UTC, emagdalenaC2i approved these changes
Review and tested in Runbot
You can merge once solve last comment of @mreficent about post-migration

2019-06-12 10:21 UTC, MiquelRForgeFlow approved these changes
:+1:

2019-06-14 15:54 UTC, emagdalenaC2i commented
Are this ready to merge?

2019-06-14 15:57 UTC, merged