[11.0][ADD] message_security_author
OCA/social pull request #398
Opened 2019-06-20 11:13 UTC by mreficent

Message Security Author
=======================

Some modules like `mail_tracking` give the users the possibility to access to
the messages by indirect ways. Odoo have not yet regulated what the users can
do to messages because by default in Odoo no users can access to them.

Thus, this `message_security_author` enters in scene.

This module restricts who can edit/delete messages. Specifically, a message
may be edited or deleted if and only if:

- The user is who created the message previously.
- The user have special permission (is in the group `Mail Message Manager`)

2019-06-21 07:25 UTC, lreficent commented
travis should be fixed with https://github.com/OCA/social/pull/400

2019-06-21 10:10 UTC, mreficent commented
thanks

2019-06-21 10:20 UTC, LoisRForgeFlow reviewed
Some comments inline

2019-06-21 10:20 UTC, lreficent commented on message_security_author/models/mail_message.py
> +        elif message_manager_group in user.groups_id:
why not `user.has_group('message_security_author.group_mail_message_manager')`?

2019-06-21 10:20 UTC, lreficent commented on message_security_author/models/mail_message.py
> +        user = self.env["res.users"].sudo().browse(self._uid)
why not `self.env.user`?

2019-06-21 10:48 UTC, LoisRForgeFlow approved these changes
:+1:

2019-07-17 11:06 UTC, HviorForgeFlow approved these changes

2019-09-06 08:00 UTC, yajo requested changes
> Some modules like `mail_tracking` give the users the possibility to access to
> the messages by indirect ways. Odoo have not yet regulated what the users can
> do to messages because by default in Odoo no users can access to them.

If this is true, it should be considered a security problem in `mail_tracking` (and fixed there too)?

What exactly do you mean by "accessing messages by indirect ways"? :thinking:

2019-09-06 08:00 UTC, yajo commented on message_security_author/models/mail_message.py
> +    def write(self, vals):
You should overload methods `check_access_rights` (by model) and/or `check_access_rule` (by record; according to your module description you should use this one possibly).

2019-09-06 08:00 UTC, yajo commented on message_security_author/models/mail_message.py
> +            rec = super(Message, self).write(vals=vals)
Calling to super 6 times is a bit ugly. Can't you think in another way?

2019-09-06 08:00 UTC, yajo commented on message_security_author/models/mail_message.py
> +                'message_security_author.group_mail_message_manager'):
This can be done through normal permission system, no need to hardcode it.

2019-09-06 08:00 UTC, yajo commented on message_security_author/models/mail_message.py
> +        elif not self.filtered(lambda m: user not in m.author_id.user_ids):
This also.

2019-09-06 08:00 UTC, yajo commented on message_security_author/models/mail_message.py
> +                vals.get('res_id'):
This is weird... So if I cannot write a crm.lead, to be able to write it I just have to modify these 2 fields? :roll_eyes:

2019-09-06 08:00 UTC, yajo commented on message_security_author/models/mail_message.py
> +                'message_security_author.group_mail_message_manager'):
This can be done with normal permissions.

2019-09-06 08:00 UTC, Yajo commented on message_security_author/readme/INSTALL.rst
> +To install this module, simply follow the standard install process.
You can remove this file. It's more targeted to non-obvious installation cases.

2022-03-20 12:29 UTC, closed without merging