[FIX] mail_debrand: Add development_status
OCA/social pull request #408
Opened 2019-07-05 00:55 UTC by max3903

2019-07-05 02:15 UTC, max3903 commented
This was just an example to show the process in an event (Meetup Odoo in Querétaro, Mexico).

2019-07-05 07:57 UTC, pedrobaeza approved these changes
OK, then let's showcase the OCA Bot merger :wink:

2019-07-05 07:57 UTC, pedrobaeza requested changes
Oh, wait, you can't put that development status without a maintainer. Please put me for example.

2019-07-05 07:58 UTC, pedrobaeza commented
(note: there's a pending task for the linter to detect these things)

2019-07-05 17:19 UTC, pedrobaeza approved these changes

2019-07-11 14:12 UTC, etobella approved these changes
LGTM

2019-07-11 14:13 UTC, pedrobaeza commented
I'm going to use normal GitHub flow as I need to squash both commits.

2019-07-11 14:13 UTC, merged

2019-07-11 14:13 UTC, pedrobaeza commented
Note also that this is not a bug. If you don't indicate any development status, Beta will be the default.