[12.0][WIP][ADD] - new module: mail template substitute
OCA/social pull request #420
Opened 2019-07-23 15:46 UTC by sbejaoui

This module allows you to create substitution rules for mail templates.
A typical use case is to replace a standard template by alternative templates
when some conditions are met. For instance, it allows to configure alternate
templates for different companies.

Todo:

- [ ] Add unit tests

2019-07-23 15:46 UTC, sbejaoui commented
ping @sbidoul

2019-07-30 08:22 UTC, gva-acsone commented
Very interesting module !

Two small observations:

1. IMO, the list of available substitute mail templates should be limited to the templates that relate to the same model. It should be impossible to select an 'invoice' mail template as substitute for a 'sales order' mail template.

2. We need to find a solution to combine the mail template substitute module and the report substitute module. Indeed, there is a use case that is still problematic --> When a mail template substitute is applicable, Odoo always takes the report related to that mail template substitute and adds it as an attachment, even though this report has substitutes itself that should be applied. 

Odoo should start by looking at the mail templates substitutes and choose the right mail template to apply. Afterwards, it should look at the report related to the mail template and look at the report substitutes to choose the right report to add as an attachment.

2019-07-30 13:31 UTC, sbejaoui commented
Thank you @gva-acsone for your feedback.

> 1. IMO, the list of available substitute mail templates should be limited to the templates that relate to the same model. It should be impossible to select an 'invoice' mail template as substitute for a 'sales order' mail template.

Fixed

> 2. We need to find a solution to combine the mail template substitute module and the report substitute module. Indeed, there is a use case that is still problematic --> When a mail template substitute is applicable, Odoo always takes the report related to that mail template substitute and adds it as an attachment, even though this report has substitutes itself that should be applied.
> 
> Odoo should start by looking at the mail templates substitutes and choose the right mail template to apply. Afterwards, it should look at the report related to the mail template and look at the report substitutes to choose the right report to add as an attachment.

I made the `mail_template_substitute` depends on `report_substitute` and it resolved the use case you mentioned.

2019-08-01 09:42 UTC, gva-acsone commented
Thanks you @sbejaoui for the two modifications, all good for me.

Three other observations:

1° When we manually send a new message based on a template (chatter), the report substitution is not automatically done.

2° If the original email template doesn't have a related report template, the related report of the substitution email template will be ignored.

3° If a mail template is added as an action in the list view, the user has the ability to choose whether he wants to send the email to the selected records or the default search. If he selects the default search, the substitution only applies to the selected records.

2019-08-30 10:52 UTC, gva-acsone commented
@sbejaoui : 
The first two points are good for me (functional test), thanks for the correction !

2019-10-01 13:47 UTC, rousseldenis requested changes
Code review. Some comment.

Don't forget to change oca_dependencies before merge

2019-10-01 13:47 UTC, rousseldenis commented on mail_template_substitute/__manifest__.py
> +    "website": "https://github.com/acsone/social",
Change this according to https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py

2019-10-01 14:10 UTC, RobinetDenisAcsone approved these changes
Code review, LGTM

2020-02-11 10:08 UTC, sbejaoui commented
@rousseldenis , can you update your review please

2020-02-11 12:40 UTC, rousseldenis approved these changes
Code review

2020-02-11 13:11 UTC, sbejaoui commented
@OCA/core-maintainers , This PR is ready to merge

2020-03-07 08:42 UTC, sbidoul commented
/ocabot merge patch

2020-03-07 08:57 UTC, merged