13.0 mig mail activity done
OCA/social pull request #445
Opened 2019-10-16 19:42 UTC by emagdalenaC2i

2019-10-16 20:52 UTC, emagdalenaC2i commented
@ageficent @jbeficent could you review this PR?

2019-10-17 15:49 UTC, AdriaGForgeFlow requested changes
When I try to Mark as done one activity Odoo throws the following error:
![image](https://user-images.githubusercontent.com/44768500/67025434-50404d80-f106-11e9-9a03-5b74a45efdf3.png)

It seems that Odoo's original function action_feedback now has two arguments:
`def action_feedback(self, feedback=False, attachment_ids=None):`

2019-10-17 18:57 UTC, emagdalenaC2i commented
@ageficent fixed

2019-10-18 06:13 UTC, AdriaGForgeFlow approved these changes
Functional test and code review :+1:

2019-10-24 10:57 UTC, jarroyomorales commented on mail_activity_done/models/res_users.py
> +        # Here we totally override the method. Not very nice, but
Maybe we could add a context here to use the old method?

if self.env.context.get('use_old_systray_get_activities', False):
    return super().systray_get_activities

2019-10-28 05:20 UTC, emagdalenaC2i commented
@pegonzalezspesol and @jbeficent Could you review this PR?

2019-10-28 05:29 UTC, jbeficent commented
@ageficent @hveficent @joansis can you review?

2019-11-14 10:44 UTC, pegonzalezspesol commented
@emagdalenaC2i , as soon as I click on "Done" on an activity I get next issue

![image](https://user-images.githubusercontent.com/55989612/68850318-18f89880-06d4-11ea-9033-5f479e609a9d.png)

2019-11-14 11:33 UTC, hveficent commented
I think this module does not make sense anymore. On v13 mail activities are DELETED when they are done, and a message is posted with proper Activity kind, Note and Feedback.

2019-11-14 11:35 UTC, hveficent commented
You must override method _action_done instead of action_feedback.

2019-11-14 12:24 UTC, emagdalenaC2i commented
@pegonzalezspesol I can't reproduce that error. The done button works fine for me.
Can you explain the steps to follow?

2019-11-14 12:46 UTC, pegonzalezspesol commented
> @pegonzalezspesol I can't reproduce that error. The done button works fine for me.
> Can you explain the steps to follow?
> Have you tried it on Runbot or have you installed it?
On Runbot. Steps:
1.- Schedule an Activity
2.- Mark as Done
3.- Write a feedback
4.- Click on Done
![image](https://user-images.githubusercontent.com/55989612/68858311-0f2b6100-06e5-11ea-9104-8589d5a0adaf.png)

2019-11-14 15:13 UTC, hveficent commented
feedback field has been removed from mail.activity model. Now feedback is prompt on mail message, so write feedback field break module.
We might store that mail message reference on done activities to not lose that information.
js parts has been refactores (camelCase function naming) as we are overwriting tat parts I would be interest to be as similar as new version.

2019-12-24 11:04 UTC, AdriaGForgeFlow commented
Travis is red, could you check? Thanks!

2020-01-27 14:12 UTC, HviorForgeFlow commented
@emagdalenaC2i could you close it? Thanks,

2020-01-27 14:36 UTC, closed without merging