[13.0][MIG] mail_tracking: Migration to 13.0
OCA/social pull request #464
Opened 2019-11-18 10:55 UTC by Tardo

Cc @tecnativa TT19769

2019-11-18 11:00 UTC, pedrobaeza commented
Please squash `fixup` commits together and also administrative commits with the first non-administrative one.

2019-11-18 12:58 UTC, pedrobaeza commented
@Tecnativa/developers

2019-11-19 13:16 UTC, yajo reviewed
Good overall.

2019-11-19 13:16 UTC, yajo commented on mail_tracking/views/mail_tracking_email_view.xml
> +                              decoration-info="event_type in ('unsub', 'click', 'open')">
Use always a `set()` when it's going to be used with the `in` operator.

\* I'm not sure if it affects here, as this is going to be evaluated in JS, but I guess if there is any optimization present in the pyjs stuff, it will have this into account... :thinking:

2019-11-19 13:16 UTC, yajo commented on mail_tracking/views/mail_tracking_email_view.xml
> +              decoration-danger="state in ('rejected', 'spam', 'bounced', 'soft-bounced', 'error')"
Use `set()` also.

2019-11-19 13:16 UTC, yajo commented on mail_tracking/views/mail_tracking_event_view.xml
> +              decoration-info="event_type in ('unsub', 'click', 'open')">
Use `set()` also.

2019-11-19 13:16 UTC, yajo commented on mail_tracking/__manifest__.py
> +    "author": "Tecnativa, " "Odoo Community Association (OCA)",
I guess this is better as a single string, or parenthesized. See https://github.com/OCA/partner-contact/pull/793.

2019-11-19 13:18 UTC, pedrobaeza commented on mail_tracking/views/mail_tracking_email_view.xml
> +                              decoration-info="event_type in ('unsub', 'click', 'open')">
I suppose you mean `decoration-info="event_type in {'unsub', 'click', 'open'}"`.

Good question about this being evaluated correctly... I suppose it should work, but not sure what is more efficient on JS side.

2019-11-19 13:38 UTC, Yajo commented on mail_tracking/views/mail_tracking_email_view.xml
> +                              decoration-info="event_type in ('unsub', 'click', 'open')">
Yes, I mean that.

2019-11-19 17:26 UTC, Tardo commented on mail_tracking/views/mail_tracking_email_view.xml
> +                              decoration-info="event_type in ('unsub', 'click', 'open')">
Can't use 'set' in this place...

You can try:
```javascript
py.evaluate(py.parse(py.tokenize("{'foo', 'bar'}"))).toJSON()

py.evaluate(py.parse(py.tokenize("('foo', 'bar')"))).toJSON()
```

2019-11-20 08:24 UTC, Yajo commented on mail_tracking/views/mail_tracking_email_view.xml
> +                              decoration-info="event_type in ('unsub', 'click', 'open')">
I see, then doubt solved, thanks!

2019-11-20 08:25 UTC, yajo approved these changes

2019-11-20 08:26 UTC, Yajo commented
Please check travis.

2019-12-23 09:19 UTC, astirpe commented on mail_tracking/hooks.py
> +def column_exists(cr, table, column):
You can reuse the `column_exists()` from the `odoo.tools`:

```python
from odoo.tools import column_exists

2019-12-24 12:52 UTC, Tardo commented
Thanks! changes done.

2019-12-24 14:06 UTC, yajo approved these changes
Ready to merge IMO.

2020-01-07 18:12 UTC, pedrobaeza approved these changes

2020-01-07 18:12 UTC, pedrobaeza commented
/ocabot merge

2020-01-07 22:38 UTC, pedrobaeza commented
/ocabot merge

2020-01-07 22:57 UTC, pedrobaeza commented
@sbidoul any idea which can be the error here?

https://travis-ci.org/OCA/social/jobs/633988361#L1004

2020-01-08 07:40 UTC, sbidoul commented
Very strange error, never seen that one.

2020-01-08 09:01 UTC, pedrobaeza commented
Me neither, let's try again...

/ocabot merge

2020-01-08 09:36 UTC, sbidoul commented on mail_tracking/models/res_partner.py
> +        partners_no_mail.write({"email_score": 50.0})
write in compute?

2020-01-28 11:10 UTC, Tardo commented
Fixes applied and conflicts resolved

2020-01-28 11:41 UTC, Yajo commented
/ocabot merge

2020-01-30 10:41 UTC, Yajo commented
@Tardo rebase please.

2020-02-05 13:49 UTC, HviorForgeFlow requested changes
I'm running in troubles installing this module:
```
2020-02-05 13:46:31,707 40 ERROR prod odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'db_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 434, in load_modules
    registry.setup_models(cr)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 258, in setup_models
    dependencies[field] = set(field.resolve_depends(model))
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 684, in resolve_depends
    for index, fname in enumerate(dotnames.split('.')):
AttributeError: 'list' object has no attribute 'split'
```
Where key 'db_name' is my database name.

Couldn't figure out how this occurs.

2020-02-05 15:52 UTC, Tardo commented
rebased

@HviorForgeFlow sorry, a problem with '_primary_email' member variable.

2020-02-05 15:53 UTC, HviorForgeFlow approved these changes

2020-02-05 15:56 UTC, pedrobaeza commented
/ocabot merge

2020-02-05 16:11 UTC, pedrobaeza commented
@Tardo please fix isort. You should configure the pre-commit in your local for avoiding these problems.

2020-02-05 16:34 UTC, Tardo commented
Done

2020-02-05 16:38 UTC, pedrobaeza commented
/ocabot merge

2020-02-05 16:59 UTC, merged