[11.0][FIX][mail_restrict_follower_selection] fixes a corner case where you could send an email to a partner that you are not supposed to.
OCA/social pull request #492
Opened 2020-01-23 14:20 UTC by JordiBForgeFlow

2020-01-23 14:21 UTC, JordiBForgeFlow commented
cc @etobella

2020-01-23 14:21 UTC, JordiBForgeFlow commented
@AdriaGForgeFlow @LoisRForgeFlow

2020-01-23 14:36 UTC, etobella requested changes

2020-01-23 14:36 UTC, etobella commented on mail_restrict_follower_selection/models/mail_thread.py
> +                    )
You are computing this domain several times, maybe you should declare it before the first key.

2020-01-23 14:39 UTC, etobella approved these changes
LGTM :+1:

2020-01-23 15:01 UTC, jarroyomorales approved these changes

2020-01-23 15:06 UTC, AdriaGForgeFlow approved these changes

2020-01-27 12:18 UTC, JordiBForgeFlow commented
/ocabot merge

2020-01-27 12:32 UTC, merged