travis conf: add runnig_env
OCA/social pull request #516
Opened 2020-03-09 10:32 UTC by simahawk

2020-03-09 13:45 UTC, yajo requested changes

2020-03-09 13:45 UTC, Yajo commented on .travis.yml
> +  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc - travis_install_nightly
Did you mean this?

```suggestion
  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
  - travis_install_nightly
```

2020-03-09 14:37 UTC, simahawk commented
@Yajo yeah, messed up via web editor :sweat_smile:  Fixed (to be squashed on merge).

2020-03-10 10:18 UTC, merged

2020-03-10 10:18 UTC, Yajo commented
Fast-tracked as it fixes the branch.