Migrate mail_optional_follower_notification to 9.0
OCA/social pull request #63
Opened 2016-05-25 14:24 UTC by lmignon

2016-06-02 07:09 UTC, hbrunn commented
please get the commits from 8.0 to allow simple cherry picking of further developments in 8.0: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#howto

2016-06-11 22:16 UTC, rafaelbn commented
Waiting for the fix in order to test it. Thanks

2016-06-13 07:34 UTC, lmignon commented
@hbrunn This branch is based on the one merged in 8.0. It seems that the original commits have been squashed when the branch has been merged. Why? I've asked @adrienpeiffer if he is aware of this squash and he isn't....  Now I've to redo my branch and I'm not happy with that.

2016-06-13 07:39 UTC, hbrunn commented
@lmignon looking at the commit log, it seems I'm the culprit. Then ignore my request, and I'll look into how to avoid those mistakes in the future. Apologies for the noise.

2016-06-13 07:40 UTC, hbrunn commented
everything else looks good btw, :+1:

2016-06-13 07:41 UTC, lmignon commented
@hbrunn Rebase done...

2016-06-13 07:53 UTC, lmignon commented
@hbrunn 

> @lmignon looking at the commit log, it seems I'm the culprit. Then ignore my request, and I'll look into how to avoid those mistakes in the future. Apologies for the noise.

I don't blame you, In this case, the 'rebase' was easy. (reset --hard oca/9.0 + cherry-pick commits on 8.0 + cherry-pick specific commits on 9.0 = 5 commands :smirk: )

Unfortunately, it seems that I've to fix my branch...

2016-06-13 09:20 UTC, lmignon commented
@hbrunn Can yout put the label WIP? I've to fix the tests but didn't have time now.

2016-10-04 14:20 UTC, rafaelbn commented
Hi @lmignon , which is the **difference** between this module and configure the same in Settings - Email - Subtypes?

I know that this is a migration, but in fact module in v8 was not necessary as you can configure it.

2016-10-24 08:10 UTC, adrienpeiffer commented
@rafaelbn What do you mean about ```configure the same``` ?
 We can use this module without a subtype. it's not the same feature. Here, the user can simply decide if he want to notify follower or not without any configuration.

2016-10-24 08:30 UTC, adrienpeiffer requested changes

2016-10-24 08:30 UTC, adrienpeiffer commented on mail_optional_follower_notification/models/res_partner.py
> +            message, force_send=False, user_signature=True)
Don't propagate default value of named arguments

2016-10-24 08:43 UTC, dreispt commented
I did not read the code, but from the module description, this seems to be the same feature as the standard "Log a message" - it writes a message on the Chatter without sending it to the Followers.

2016-10-25 07:25 UTC, adrienpeiffer commented
@dreispt You have the possibility to define some recipent but you can exclude followers.

2016-11-19 15:01 UTC, dreispt approved these changes
I suggest a better description:
"When sending a message in a document's mail chatter, all Followers are notified.
This feature allows to uncheck the notify followers checkbox, and have the notification sent only to selected people.
Beware that the message will still be visible to all followers when viewing the document."

But not blocking and implementation LGTM

2017-02-13 11:16 UTC, lmignon commented
rebased

2017-03-06 18:11 UTC, hbrunn commented on mail_optional_follower_notification/tests/test_mail_optional_follower_notifications.py
> +            if record.notified_partner_ids.ids == [self.partner_03.id] and\
this should be `needaction_partner_ids` by now: https://github.com/OCA/OCB/blob/9.0/addons/mail/models/mail_message.py#L950

2017-03-17 10:09 UTC, hbrunn commented on mail_optional_follower_notification/tests/test_mail_optional_follower_notifications.py
> +            if record.notified_partner_ids.ids == [self.partner_03.id] and\
@lmignon can you fix the test? Then we can merge I think

2017-03-17 10:52 UTC, lmignon commented
@hbrunn I've edited the file on github If tests are OK I'll squash my last commits

2017-03-17 11:19 UTC, hbrunn commented
yay, worked. I'll count @adrienpeiffer as a +1 because his comment was addressed too, so I'll merge after the squashing

2017-03-17 12:26 UTC, lmignon commented
@hbrunn Commit squahed...

2017-03-17 12:36 UTC, merged