[13] [FIX] suggested restrict followers for a model
OCA/social pull request #648
Opened 2020-12-15 11:19 UTC by angelmoya

With module mail_restrict_follower_selection.

You can restrict only the followers for a certain record type (or have different restrictions for different record types), creating a parameter `mail_restrict_follower_selection.domain.$your_model`

This will work on wizard invite, but do not work on mail.thread _message_add_suggested_recipient...

I update this method to pass context, this way _mail_restrict_follower_selection_get_domain method know model to apply domain.

2020-12-21 15:24 UTC, angelmoya commented
@etobella can you check this?

2020-12-21 20:32 UTC, etobella requested changes
Ouch!!! So true, however, it was solved on 12.0 using another solution, can you cherry-pick it?

https://github.com/OCA/social/commit/73d8d0ee24a45be4fb22a0c0af2380c08cc89ba5#diff-0c193b4d1b0323b8f2d3e99a92268162a82d3eaadf1c3bbe56f075b04e08c548

2020-12-22 09:39 UTC, angelmoya commented
@etobella 

Nice! I did cherry-pick, also I add tests and fix pre-commit, Because I had an error with pre-commit...

I'm not sure about this pre-commit fix is right or must be done here

2021-01-13 08:26 UTC, FernUni-UniDistance approved these changes
LGTM

2021-01-13 08:50 UTC, etobella approved these changes

2022-01-21 08:31 UTC, etobella commented
@angelmoya Can you fix the conflicts?

2022-01-21 08:31 UTC, etobella commented
@angelmoya Can you fix the conflicts?

2022-03-11 13:40 UTC, rafaelbn commented
/ocabot rebase

2022-03-11 13:40 UTC, rafaelbn commented
@angelmoya please last review a let get this merged! Ping me when done ! 😄

2022-03-11 13:42 UTC, rafaelbn commented
/ocabot merge major

2022-04-05 08:04 UTC, closed without merging

2022-04-05 08:04 UTC, etobella commented
Closing as Superseed is being merged