[MIG] mail_activity_board: Migration to 14.0
OCA/social pull request #661
Opened 2021-01-22 09:38 UTC by SodexisTeam

2021-01-22 09:44 UTC, atchuthan commented
/home/runner/work/social/social/mail_activity_board/static/src/components/chatter_topbar/chatter_topbar.js
  28:33  error  'ev' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

>> Please let me know how to resolve this pre-commit as Odoo uses ev as parameter in the method
https://github.com/odoo/odoo/blob/14.0/addons/mail/static/src/components/chatter_topbar/chatter_topbar.js#L47-L63

2021-03-07 21:38 UTC, max3903 commented on mail_activity_board/views/mail_activity_view.xml
> +                                            <span><i class="fa fa-clock-o" /></span>
```
2021-03-07 21:30:56,685 218 WARNING odoodb odoo.addons.base.models.ir_ui_view: A <i> with fa class (fa fa-clock-o) must have title in its tag, parents, descendants or have text
```

2021-03-12 05:18 UTC, atchuthan commented on mail_activity_board/views/mail_activity_view.xml
> +                                            <span><i class="fa fa-clock-o" /></span>
@max3903 the warning is resolved now

2021-05-13 06:48 UTC, emagdalenaC2i commented
@SodexisTeam There is a issue with pre-commit. Please, could you fix it?

2021-05-17 09:38 UTC, atchuthan commented
@emagdalenaC2i 
The definition is based on Odoo module. https://github.com/OCA/social/pull/661#issuecomment-765278859

Any suggestion is much appreciated.

2021-08-17 11:42 UTC, manuelregidor approved these changes
It seems to be working fine.

2021-08-31 15:04 UTC, ypapouin requested changes
LGTM - Code Review
Please fix pre-commit

2021-09-02 06:18 UTC, atchuthan commented
pre-commit fixed and squashed commits.
Ready for review.
@emagdalenaC2i @max3903 @ypapouin @pedrobaeza

2021-09-02 08:06 UTC, MiquelRForgeFlow approved these changes
LGTM

2021-09-02 08:10 UTC, MiquelRForgeFlow reviewed
Please :)

2021-09-02 08:10 UTC, MiquelRForgeFlow commented on mail_activity_board/readme/CONTRIBUTORS.rst
> +  * Miquel Raïch (miquel.raich@eficent.com)
```suggestion
* `ForgeFlow <https://www.forgeflow.com>`_:

  * Miquel Raïch (miquel.raich@forgeflow.com)
```

2021-09-02 08:10 UTC, MiquelRForgeFlow commented on mail_activity_board/models/mail_activity.py
> +# Copyright 2018 Eficent Business and IT Consulting Services, S.L.
```suggestion
# Copyright 2018 ForgeFlow S.L.  <https://www.forgeflow.com>
```

2021-09-02 08:12 UTC, ypapouin approved these changes
LGTM

2021-09-02 09:02 UTC, HaraldPanten approved these changes
LGTM if you change Eficent/Forgeflow 👍

2021-09-02 09:47 UTC, atchuthan commented
> LGTM if you change Eficent/Forgeflow

Done changes

2021-09-21 10:50 UTC, angelmoya approved these changes
:+1:

2021-09-21 20:37 UTC, emagdalenaC2i approved these changes

2021-10-12 21:20 UTC, gaikaz approved these changes

2021-10-13 07:55 UTC, atchuthan approved these changes

2021-10-13 07:59 UTC, pedrobaeza commented
/ocabot merge nobump

2021-10-13 09:38 UTC, merged

2022-04-04 17:53 UTC, rafaelbn commented
/ocabot migration mail_activity_board