[13.0][FIX] mail_tracking: Store cc
OCA/social pull request #683
Opened 2021-03-01 22:06 UTC by Tardo

Fixes an error when saving "mail_cc" and "mail_to" values in the message.

cc @tecnativa TT28517

2021-03-02 08:06 UTC, pedrobaeza requested changes
Check also Travis

2021-03-02 08:06 UTC, pedrobaeza commented on mail_tracking/models/mail_thread.py
> +        message.write(
Can we avoid this double writing? This one is critical due to the high volume of the messages, so we shouldn't write several times and do it at message creation.

2021-03-02 12:25 UTC, Tardo commented
Thanks! changes done :)

2021-03-02 19:06 UTC, pedrobaeza approved these changes

2021-03-09 08:33 UTC, Yajo approved these changes

2021-03-09 08:33 UTC, Yajo commented
/ocabot merge patch

2021-03-09 08:43 UTC, merged