[MIG][15.0]mail_activity_board
OCA/social pull request #802
Opened 2021-11-18 09:14 UTC by JoanMForgeFlow

Standard migration to v15

2021-11-18 09:36 UTC, AaronHForgeFlow commented
@OCA/social-maintainers  can someone please approve the workflow to run here? Thanks in advance.

2021-11-18 11:23 UTC, MiquelRForgeFlow approved these changes

2021-11-18 16:50 UTC, AaronHForgeFlow requested changes
Got an error when installing contacts and creating an activity in a partner. That is not happening if I uninstall the module:
![2021-11-18_17-48](https://user-images.githubusercontent.com/19620251/142459898-0eb0ddf9-eddf-41fc-aeb6-29ac08d6c4ea.png)

2021-11-22 11:35 UTC, MiquelRForgeFlow commented on mail_activity_board/static/src/components/chatter_topbar/chatter_topbar.js
> +         * @privatez
```suggestion
         * @private
```

2021-11-22 12:03 UTC, AaronHForgeFlow approved these changes
Functional tests :+1:

2021-11-22 12:31 UTC, JoanMForgeFlow commented
Functionally, the module works as it should, but the pre-commit fails with the following error:

` 3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`

Anyone have an idea how to solve it?
Thanks in advance
@Tardo 
@MiquelRForgeFlow 
@AaronHForgeFlow

2021-11-22 14:28 UTC, AaronHForgeFlow commented
I think this may be related to https://github.com/OCA/oca-addons-repo-template/issues/85 @Yajo

2021-11-26 16:30 UTC, AaronHForgeFlow commented
> I think this may be related to [OCA/oca-addons-repo-template#85](https://github.com/OCA/oca-addons-repo-template/issues/85) @Yajo

after some research, it seems the .js files must be renamed to esm.js. So please diregard my previous message.

2021-11-29 08:22 UTC, JoanMForgeFlow commented
> > I think this may be related to [OCA/oca-addons-repo-template#85](https://github.com/OCA/oca-addons-repo-template/issues/85) @Yajo
> 
> after some research, it seems the .js files must be renamed to esm.js. So please diregard my previous message.

Solved! Thanks

2021-11-29 08:28 UTC, AaronHForgeFlow approved these changes

2021-11-29 08:35 UTC, dreispt commented
/ocabot merge nobump

2021-11-29 08:39 UTC, merged

2022-04-04 17:53 UTC, rafaelbn commented
/ocabot migration mail_activity_board