[FIX] Added a functionlity for loge not can see with a condition.
OCA/social pull request #905
Opened 2022-05-09 09:45 UTC by AmmarOfficewalaSerpentCS

2022-05-09 09:46 UTC, AmmarOfficewalaSerpentCS commented
@dreispt , @Chandresh-OSI , 
can you Please review this PR ?

2022-05-31 09:36 UTC, dreispt requested changes

2022-05-31 09:36 UTC, dreispt commented on mail_allow_portal_internal_note/models/res_users.py
> +    def portal_can_see_internal_messages(self, res_model, res_id):
Convert this to a computed field on `mail.thread`

2022-05-31 09:36 UTC, dreispt commented on mail_allow_portal_internal_note/static/src/js/composer.js
> +                    this.$(".o_portal_chatter_log_note_btn").addClass("o_hidden");
Use the QWeb template to add the `o_hidden` depending on the message thread computed value.

2022-05-31 09:37 UTC, dreispt requested changes
@AmmarOfficewalaSerpentCS I believe this implementation can be simplified, if we place the business logic in the right place.

2022-12-04 12:32 UTC, closed without merging