[15.0][MIG] mass_mailing_resend: Migration to 15.0
OCA/social pull request #989
Opened 2022-11-03 14:33 UTC by victoralmau

Migration to 15.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT40296

2022-11-03 19:31 UTC, pedrobaeza commented
/ocabot migration mass_mailing_resend

2022-11-03 19:38 UTC, pedrobaeza requested changes
Testing on runboat, the button "Emails sent" is not shown on draft state, so the text saying that you can resend to all removing the recipients in it it's not true. We should restore button visibility in this module, plus maybe adding a test for being sure about the statement in that label (already sent not sent again).

2022-11-04 07:54 UTC, victoralmau commented
Changes done.

2022-11-08 08:33 UTC, pedrobaeza commented
I think you haven't understood me... The banner is now shown on `sent` state, while it should only be shown after pressing resend (and being on draft state). The problem was that on draft state, no "N Sent" smart-button is shown, so you are not able to remove any of them for resending the mail to them.

2022-11-08 13:05 UTC, victoralmau commented
Ok sorry, I think I know what you initially meant.
Changes done.

2022-11-08 19:48 UTC, pedrobaeza commented on mass_mailing_resend/views/mailing_mailing_views.xml
> +                        >Send</b> smart-button for removing the existing record(s).
```suggestion
                        >Sent</b> smart-button for removing the existing record(s).
```

2022-11-08 19:48 UTC, pedrobaeza commented on mass_mailing_resend/views/mailing_mailing_views.xml
> +                    attrs="{'invisible': ['|', ('state', '!=', 'draft'),('sent', '=', 0)]}"
No need of this diff

2022-11-09 07:43 UTC, pedrobaeza approved these changes

2022-11-09 07:43 UTC, pedrobaeza commented on mass_mailing_resend/i18n/es.po
> +"masivo a destinatarios ya enviados, pulse en el botón <b>Enviar</"
```suggestion
"masivo a destinatarios ya enviados, pulse en el botón <b>Enviados</"
```

2022-11-15 12:45 UTC, CarlosRoca13 approved these changes
Test and code review :+1:

2022-11-16 19:52 UTC, pedrobaeza commented
/ocabot merge nobump

2022-11-16 19:59 UTC, merged